export const data = [
    {
        id:0,
        image: 'john-wick.png',
        alt: 'john-wick',
        title: 'John Wick',
        rating: '9',
        time: '2020/08/01',
        timeFilter: new Date(2020 , 8 , 1),
        text1:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        reviewTitle: 'Best movie of the century',
        writer: 'Αναστάσιος Σωτηριάδης',
        type: 'movie',
        subtype: 'action'
    },
    {
        id:1,
        image: 'bullet-train.png',
        alt: 'john-wick',
        title: 'Bullet Train',
        rating: '4.2',
        time: '2021/12/12',
        timeFilter: new Date(2021 , 8 , 1),
        text1:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        reviewTitle: 'Hollywood flop',
        writer: 'Αναστάσιος Σωτηριάδης',
        type: 'movie',
        subtype: 'action'
    },
    {
        id:2,
        image: 'noah.png',
        alt: 'john-wick',
        title: 'Noah',
        rating: '8.5',
        time: '2022/08/01',
        timeFilter: new Date(2022 , 8 , 1),
        text1:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        reviewTitle: 'A good movie that lacks respect',
        writer: 'Αναστάσιος Σωτηριάδης',
        type: 'movie',
        subtype: 'action'
    },
    {
        id:3,
        image: 'shoot-em-up.png',
        alt: 'john-wick',
        title: 'Shoot \'em up',
        rating: '9.8',
        time: '2020/08/01',
        timeFilter: new Date(2020 , 8 , 1),
        text1:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        reviewTitle: 'A dark peak into our future',
        writer: 'Αναστάσιος Σωτηριάδης',
        type: 'movie',
        subtype: 'action'
    },
    {
        id:4,
        image: '6-underground.png',
        alt: 'john-wick',
        title: '6 Underground',
        rating: '7.1',
        time: '2020/08/01',
        timeFilter: new Date(2020 , 8 , 1),
        text1:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        reviewTitle: 'An enjoyable way to spend your evening',
        writer: 'Αναστάσιος Σωτηριάδης',
        type: 'movie',
        subtype: 'action'
    },
    {
        id:5,
        image: 'your-honor.png',
        alt: 'john-wick',
        title: 'Your Honor',
        rating: '5.5',
        time: '2023/04/03',
        timeFilter: new Date(2023 , 4 , 3),
        text1: 'Το your Honor αποτελεί την τηλεοπτική επιστροφή του Bryan Cranston(breaking bad) και είναι μια σειρά στην οποία καλείται ο θεατής να μπει στην θέση του πρωταγωνιστή για τα πράγματα που θα έκανε αν το παιδί του έμπαινε σε μια τέτοια επικίνδυνη κατάσταση. Από τα πρώτα κιόλας επεισόδια η σειρά σε βάζει σε ένα πολύ σκοτεινό mood με μια ταυτόχρονη καταθλιπτική διάθεση. Η πόλη στην οποία πραγματοποιούνται τα γεγονότα είναι η νέα Ορλεάνη γνωστή πόλη για την έντονη παρουσία των έγχρωμων ανθρώπων και των γκέτο. Γενικά η σειρά δεν έχει και τις τρέλες ερμηνείες που θα έκανε τον θεατή να την θυμάται για όλη του την ζωή όμως αποτελεί μια ακόμα ελκυστική και ποιοτική σειρά. Ο Bryan Cranston δεν μπορούμε να πούμε ακριβώς ότι βγαίνει εντελώς έξω από τα νερά του καθώς μπαίνει σε έναν ακόμα γνωστό ρόλο των ειδικών συνθηκών. Δηλαδή τις συνθήκες στις οποίες ο πρωταγωνιστής αναγκάζεται να κάνει πράξεις με τις οποίες οι αξίες του και τα πιστεύω του δεν είναι 100% σύμφωνα. Σε πολλά σημεία η σειρά έχει κάποια νεκρά σημεία στα οποία αναρωτιέται ο θεατής πως γίνεται να συνέβη αυτό καθώς η σειρά δεν δικαιολογεί 100% όλα τα γεγονότα που συμβαίνουν.',
        subtitle1: 'Η αξιολόγηση των ηθοποιών',
        text2: 'Πέρα από τους βασικούς πρωταγωνιστές δηλαδή τον Bryan Cranston και Michael Stuhlbarg κανένας άλλος ηθοποιός δεν μπορούμε να πούμε ότι μας εκπλήσσει με την ερμηνεία του και δεν θα ήταν υπερβολή να πούμε ότι οι δύο πρωταγωνιστές προσπαθούν να σηκώσουν την σειρά μόνοι τους. ',
        subtitle2: 'Η διαφορά των δυο σεζόν',
        text3: 'Η σειρά ολοκληρώνεται με 2 σεζόν των 10 επεισοδίων στις οποίες δεν υπάρχει ομοιόμορφη εξέλιξη στον ενδιαφέρων της πλοκής. Με ευκολία μπορούμε να πούμε ότι στην πρώτη σεζόν σίγουρα τα επεισόδια τραβάνε περισσότερο το βλέμμα του θεατή διότι στην 2η σεζόν υπάρχει ένα μεγάλο ερωτηματικό στα πρώτα επεισόδια φτάνοντας στα όρια του και λίγο βαρετού μέχρι να αρχίσει να ξετυλίγεται  πλήρως το μυστήριο.',
        subtitle3: 'Λόγοι για να δει κάποιος την σειρά',
        text4: 'Συμπερασματικά μπορούμε να πούμε ότι η σειρά αποτελεί μια ευχάριστη περιπέτεια για τον θεατή που σίγουρα αξίζει να την δει. Επίσης ο θεατής όπως αναφέραμε έρχεται συχνά αντιμέτωπος και ο ίδιος με ηθικά διλλήματα που για κάποιους αυτό αποτελεί μεγάλο θετικό σημάδι για την αξιολόγηση μιας σειράς. Ο θεατής δεν πρέπει επειδή η σειρά ξεκινάει πολύ εντυπωσιακά να έχει υψηλές απαιτήσεις από τον σεναριογράφο σε όλη την διάρκεια της και απλά να δείξει κατανόηση σε αυτό το πολιτικό-δικαστικό θρίλερ που εξελίσσεται.Τέλος πιστεύουμε ότι η σειρά δικαίως ολοκληρώνεται στις 2 σεζόν καθώς δεν έχει κάτι περισσότερο να δείξει και τα στοιχεία που θέλει να περάσει τα καλύπτει και με το παραπάνω.    ',
        subtitle4: '',
        text5: '',
        reviewTitle: 'Μια καλή σειρά',
        writer: 'Αναστάσιος Σωτηριάδης',
        type: 'series',
        subtype: 'action'
    },
    {
        id:6,
        image: 'the-whale.png',
        alt: 'john-wick',
        title: 'The Whale',
        rating: '8',
        time: '2023/04/06',
        timeFilter: new Date(2023 , 4 , 6),
        text1: 'Το the Whale πρόκειται για μια πολυσυζητημένη ταινία που τράβηξε τα βλέμματα στην φετινή τελετή των Όσκαρ και στο τέλος έφυγε νικήτρια με ένα πολύ σημαντικό βραβείο (Α ανδρικού). Το παράδοξο της ταινίας που κάνει πολλούς ανθρώπους που δεν την έχουν δει να αναρωτιούνται πως κατάφερε να αποσπάσει αυτό το βραβείο, είναι επειδή δεν ήταν υποψήφια στην κεντρική κατηγορία της τελετής δηλαδή αυτήν της καλύτερης ταινίας.',
        subtitle1: 'Η πλοκή της ταινίας και το κεντρικό νόημά της',
        text2: 'Η ταινία εξιστορεί την ιστορία ενός υπέρβαρου ανθρώπου(Μπρένταν Φρέιζερ) στην απέλπιδα προσπάθεια του να ξανά καταφέρει να επανακτήσει την σχέση του με την μοναδική του κόρη που στην ουσία είναι ο μοναδικός άνθρωπος που νοιάζεται πραγματικά σε αυτόν τον κόσμο που του φαίνεται μάταιος. Φυσικά δεν μιλάμε απλά για έναν υπέρβαρο άνθρωπο αλλά για έναν άνθρωπο που ακουμπάει τα όριά του αποκρουστικού με τον ίδιο πολλές φορές να αναρωτιέται και να αναζητεί απαντήσεις από τρίτους αν τον βρίσκουν απαίσιο. Όλη η ταινία διαδραματίζεται σε έναν και μόνο χώρο γεγονός που κάνει την ταινία από μόνη της γοητευτική και τραβάει αμέσως τον θεατή να την παρακολουθήσει. Ο Σκηνοθέτης της ταινίας, ένα πολύ γνωστό όνομα στον χώρο της σκηνοθεσίας (Αρονοφσκυ) φαίνεται ότι επένδυσε πολλά στην ερμηνεία του πρωταγωνιστή που πέρα από καθηλωτική και συγκινητική αποτέλεσε και την ερμηνεία ζωής του ηθοποιού με τον ίδιο στο άκουσμα της νίκης του στην τελετή των Όσκαρ να μην μπορεί να αρθρώσει λέξη  από την συγκίνηση.',
        subtitle2: 'Τα κρυφά μηνύματα που υπαινίσσονται στην ταινία',
        text3: 'Η ταινία περνά πάρα πολλά νοήματα σε ότι αφορά τις κοινωνικές σχέσεις των ανθρώπων και στους δεσμούς που σχηματίζονται. Προσωπική μου άποψη γροθιά στο στομάχι ήταν η σκηνή με τον διανομέα, που κοντοστέκεται για να αντικρίσει έναν άνθρωπό που δεν έχει συναντήσει ποτέ στην ζωή του ενώ του πηγαίνει τις παραγγελίες πάρα πολλά χρονιά. Η σκηνή αυτή προσπαθεί να τονίσει τις απρόσωπες σχέσεις μεταξύ των ανθρώπων που πολλές φορές μπορεί να μην ξέρουμε τα αληθινά προβλήματα που μπορεί να αντιμετωπίζει κάποιος και να στεκόμαστε αμέτοχοί στα προβλήματά του και φυσικά η σκηνή που πραγματοποιεί το τελευταίο μάθημα με τους μαθητές του και σταματάει πια να είναι ένας απλός άνθρωπος που κρύβει το ποιος είναι και αποφασίζει να τα αποκαλύψει όλα. Πέρα από την συγκλονιστική ερμηνεία του πρωταγωνιστή σημαντικό κεφάλαιο της ταινίας αποτελεί και η κόρη του ίδιου καθώς φαίνεται πλήρως αντιδραστική και τοξική με την ίδια να κρατάει μια στάση απέχθειας απέναντι προς το πρόσωπό του και να προσπαθεί συνεχώς να εκμεταλλευτεί το επάγγελμά του πατέρα της που είναι δάσκαλος για να περάσει την τάξη.',
        subtitle3: 'Η αξιοθαύμαστη προσπάθεια του πρωταγωνιστή',
        text4: 'Ο πρωταγωνιστής της ταινίας κάνει αντιληπτό γρήγορα στους θεατές ότι έχει καταβάλλει πολύ μεγάλη προσπάθεια για να ενσαρκώσει αυτόν τον ρόλο. Ένας ρόλος που έχει τεράστιες απαιτήσεις με τις συνεχόμενες ψυχολογικές διακυμάνσεις του ίδιου. Φυσικά στην ταινία συμμετέχουν και αλλά πρόσωπά που παίζουν καθοριστικό ρόλο στην πλοκή της ταινίας, όμως ο πρωταγωνιστής με την ερμηνεία του δεν αφήνει τους αναγνώστες να προσέξουν κανέναν άλλον πάρα μόνο αυτόν και την ιστορία του. Δηλαδή από το πως ξεκίνησε, το πως κατέληξε να είναι υπέρβαρος και εν τέλει ποιο θα είναι το τέλος του. Αξίζει να αναφέρουμε ότι ένα μεγάλο σκηνοθετικό τρικ του σκηνοθέτη αλλά και ίσως και του σεναριογράφου είναι ότι οι θεατές από το πρώτο λεπτό νομίζουν ότι θα υπάρξει κάποια στιγμή που ο πρωταγωνιστής θα πει ένα μεγάλο ως εδώ και θα αρχίσει την προσπάθειά της αλλαγής του όμως αυτό δεν συνέβη ποτέ. Αντίθετα ο σεναριογράφος έχει αποφασίσει να δείξει τον πρωταγωνιστή ότι έχει πάρει μια σημαντική απόφαση να τελειώσει με έναν συγκεκριμένο τρόπο την ζωή του και δεν θέλει να κάνει καμία προσπάθεια να αλλάξει.',
        subtitle4: '',
        text5: '',
        reviewTitle: 'Ένα μικρό τεράστιο διαμάντι',
        writer: 'Αναστάσιος Σωτηριάδης',
        type: 'movie',
        subtype: 'action'
    },
    {
        id:7,
        image: 'the-mandalorian.png',
        alt: 'mandalorian',
        title: 'The Mandalorian',
        rating: '8',
        time: '2023/04/09',
        timeFilter: new Date(2023 , 4 , 9),
        text1: 'Η σειρά αποτελεί sequel του κινηματογραφικού franchise του Star Wars και λαμβάνει χώρα μερικά χρόνια αργότερα από το Return of the Jedi (1983) με την πτώση της Αυτοκρατορίας αλλά νωρίτερα από τα γεγονότα της τελευταίας τριλογίας ταινιών. Ο Mando (Pedro Pascal), απόγονος της αρχαίας φυλής των Mandalorian και αδίστακτος bounty hunter (= κυνηγός κεφαλών) περιπλανάται στον γαλαξία κυνηγώντας τους στόχους του, και συλλέγοντας τις αμοιβές του. Σε μια από τις ριψοκίνδυνες αποστολές του θα συναντήσει τον Grogou, ένα πρασινωπό πλασματάκι με μυτερά αυτιά, με το οποίο θα δημιουργήσει έναν ιδιαίτερο δεσμό που ο σκηνοθέτης Jon Favreu χτίζει άριστα και σε καθηλώνει από τα πρώτα κιόλας επεισόδια. Μαζί, Mando και Grogou ταξιδεύουν στον γαλαξία, από πλανήτη σε πλανήτη και από περιπέτεια σε περιπέτεια με την Αυτοκρατορία (ή ό,τι απέμεινε από αυτή) να καραδοκεί.',
        subtitle1: 'This is the way…',
        text2: 'Το The Mandalorian ήρθε στις ζωές μας το 2019 και με την αναπάντεχη επιτυχία του «έσωσε» το σύμπαν του Star Wars το οποίο είχε αρχίσει να «ξεθωριάζει». Η ερμηνεία του Pedro Pascal (συνυπολογίζοντας ότι δεν φαινόταν το πρόσωπό του αφού φορούσε περικεφαλαία) είναι εκπληκτική, Η βαριά φωνή, οι στοχευμένες ατάκες του και η επιβλητική κορμοστασιά του, σε συνδυασμό με την γυαλιστερή πανοπλία δομούν έναν δυναμικό χαρακτήρα αλλά ταυτόχρονα ευαίσθητο και τρυφερό. Ο Grogou αρχικά απεικονίζεται ως ένα αβοήθητο, ακίνδυνο μωρό, ωστόσο το potential των δυνατοτήτων του και η αλληλεπίδραση του με την Δύναμη (The Force) είναι ριζωμένα μέσα του (όντας απόγονος των Jedi), στοιχεία τα οποία καλείται να «ξεκλειδώσει». Κλείνοντας, αξίζει να επενδύσετε τον χρόνο σας και ας μην έχετε ιδέα από Star Wars.',
        subtitle2: '',
        text3: '',
        subtitle3: '',
        text4: '',
        subtitle4: '',
        text5: '',
        reviewTitle: 'Γκου στειλε τιτλο',
        writer: 'Θοδωρής Γκουντζιουρίδης',
        type: 'series',
        subtype: 'action'
    }
    
];
    